### ISSUE TITLE
请问提示这个是误报吗

### ISSUE THREAD

**Issue by xingmiye** [mlabalabala/box#12]
请问提示这个是误报吗
![IMG_20240202_212534](https://github.com/mlabalabala/box/assets/66361330/4b173a3f-b411-4a2d-87d7-07d06572a8f4)

**Comment by mlabalabala** [comment]
主体代码是从大佬那儿拉过来的，我也不太清楚为啥会报这个病毒了『(／_＼)大怨种』

有可能是因为，有一定安装数量后，app未备案提示的存在病毒，如果担心存在风险的话，可以换手机版(竖屏)的安装试试。如果真的担心有风险，还是试试别的大佬修改的版本吧。。。
