### ISSUE TITLE
没有字幕

### ISSUE THREAD

**Issue by caoshou** [mlabalabala/box#15]
安装到电视盒子里没有字幕，已经选择了字幕，不知道为啥就是显示不出来，装安卓虚拟机里面也没有字幕，我用的是自建小雅tvobx配置，是要做特别配置么？

**Comment by mlabalabala** [comment]
目前好像是加载不了内置字幕，自己测试的通过在线搜索然后加载字幕可以挂上

**Comment by caoshou** [comment]
我找了个TVBox v20230902-2134的版本能显示字幕，就是有点黑边，不过这个版本不能调节直播节目的地址，我只能加小雅的地址看电影。

**Comment by caoshou** [comment]
> 目前好像是加载不了内置字幕，自己测试的通过在线搜索然后加载字幕可以挂上


我找了个TVBox v20230902-2134的版本能显示字幕，就是有点黑边，不过这个版本不能调节直播节目的地址，我只能加小雅的地址看电影。

**Comment by mlabalabala** [comment]
是通过在线搜索后选择结果中的字幕无法显示吗？

**Comment by mlabalabala** [comment]
![image](https://github.com/mlabalabala/box/assets/91363385/e0c3c30b-0c36-47be-8a08-ccebd8fda2ce)


搜索的字幕能挂上

**Comment by caoshou** [comment]
> 是通过在线搜索后选择结果中的字幕无法显示吗？

是播放小雅仓库里面的mkv高清视频文件的时候， 无法播放自带的字幕，在线搜索的，因为电视盒子遥控器搜很麻烦，没试。

**Comment by mlabalabala** [comment]
我尝试了使用几个版本的q版TVbox去加载视频文件和字幕文件名相同的网络链接，好像都加载不了，提供一下这个版本（TVBox v20230902-2134）的代码提交记录或者软件包参考参考吧？

**Comment by caoshou** [comment]
> 我尝试了使用几个版本的q版TVbox去加载视频文件和字幕文件名相同的网络链接，好像都加载不了，提供一下这个版本（TVBox v20230902-2134）的代码提交记录或者软件包参考参考吧？

我是从网上搜的一个，这个我这里在安卓4上确实能显示字幕，就是字体有点不完美。
https://www.jb51.net/softs/866155.html

**Comment by caoshou** [comment]
> 我尝试了使用几个版本的q版TVbox去加载视频文件和字幕文件名相同的网络链接，好像都加载不了，提供一下这个版本（TVBox v20230902-2134）的代码提交记录或者软件包参考参考吧？


这是2个软件的截图，一个有字幕一个没有字幕。
![11](https://github.com/mlabalabala/box/assets/33174092/ec1c947b-40a8-440d-854f-01468b1c710f)
![22](https://github.com/mlabalabala/box/assets/33174092/9fc8b1ff-af74-4f05-ae94-5a00b5349cd6)
![44](https://github.com/mlabalabala/box/assets/33174092/77dd56f5-fddf-44f3-a5a6-096c1c299cf4)
![33](https://github.com/mlabalabala/box/assets/33174092/191b5df5-ae8a-410b-a79b-fb7c04b9521b)

**Comment by mlabalabala** [comment]
https://github.com/mlabalabala/box/commit/d2dc99dd357ab156ca710ab5b7245eb291e08e0c
尝试更新了加载阿里云盘的字幕，如果遇到其他问题，再提issues吧
