### ISSUE TITLE
关于jade直播版数字键选台

### ISSUE THREAD

**Issue by pm20120** [mlabalabala/box#16]
数字键选台时，一位数和两位数选台ok，按三位数后屏幕有数字显示但频道不跳转，输入四位数没任何显示。

**Comment by mlabalabala** [comment]
![image](https://github.com/mlabalabala/box/assets/91363385/c6fb3e95-5172-4d7d-8601-6ee23f8406f8)
![image](https://github.com/mlabalabala/box/assets/91363385/81ff1d97-535d-4b1a-aa65-aace0afad166)
目前直播版还存在问题

**Comment by pm20120** [comment]
黑盒新版能数字键选台了，没有上述问题，可以参考一下。不过黑盒不兼容安卓低版本，虽然更新说明讲已经支持安卓4，可是在安卓4.4虚拟机和电视盒子上都闪退。jade在安卓低版本可以运行正常。
还有一个影视仓分支派大星直播，安卓4可以运行，但不显示epg,装到安卓7上就能显示出来。也许世上没有完美的东西，想好好看个电视太难了！

**Comment by mlabalabala** [comment]
我有空看一下代码，如果可以搬过来融合的话，就尝试更新一下直播版

**Comment by mlabalabala** [comment]
https://github.com/lizongying/my-tv 这个项目也不错，里面内置了直播源

**Comment by mlabalabala** [comment]
更新：
* 跨分组换台
* 最大频道数增加到9999
* 文件名Jade_SHJ_LIVE_跨分类换台.apk

有bug可以再提issues

**Comment by pm20120** [comment]
关于界面的几点建议：
1. 希望可以把 ‘节目列表’和‘选项列表’美化一下，就是四边缩进一点，设成圆角。样式如我发的前两个图。
2. 节目列表的‘频道组’一栏宽度不够，名字较长时显示不全，希望可以加宽一点。
3.  底部的节目信息’导航条‘，我没有研究明白，有时出现，有时不出来，好像随机的？还是和EPG有关？能不能让它每次换台都出现？就像有线电视和卫星电视一样。还有导航条应该也可以设置成圆角吧？
4. ‘选项列表’中的画面比例，似乎只能调一个台，换一个台还要调整，台多时真是没办法调整。能不调整一个就设置为全部更改。（请参考影视仓的单独直播软件派大星，最新版本1.0.7）
![Screenshot_20240412_102240](https://github.com/mlabalabala/box/assets/61964890/b3518da6-e290-486b-875d-65583e4a118d)
![Screenshot_20240412_102254](https://github.com/mlabalabala/box/assets/61964890/795a85e0-cb71-49d4-b518-24d85b8045dc)
![Screenshot_20240412-100817](https://github.com/mlabalabala/box/assets/61964890/403df776-e318-443b-a492-5cf62fae4134)
![Screenshot_20240412-101000](https://github.com/mlabalabala/box/assets/61964890/7f13ce16-5e3d-4929-be3c-6b659848bf33)
![Screenshot_20240412-101009](https://github.com/mlabalabala/box/assets/61964890/afd20545-6904-4fc5-b322-d6dc7173e812)

**Comment by mlabalabala** [comment]
### EPG台标信息显示，可以选择合适自己网络环境的链接，目前在用的epg.112114.xyz域名不挂魔砝的情况下访问存在问题，当拿不到数据的时候下面的节目信息就显示不出来了 :)
![image](https://github.com/mlabalabala/box/assets/91363385/cca629a0-18b8-4833-8efb-27bd542a4398)
![image](https://github.com/mlabalabala/box/assets/91363385/f9993a94-20b6-4ca6-909b-697cfa84a151)
![image](https://github.com/mlabalabala/box/assets/91363385/f15ea84f-000a-41be-90f8-c37d730473c9)

ps: 且用且珍惜

### UI简单调整，加宽分组列表并恢复之前的圆角
![image](https://github.com/mlabalabala/box/assets/91363385/96be524e-64aa-4b92-831a-18a24fb1677b)

**Comment by pm20120** [comment]
大佬的更新速度真是快，个人感觉JADE-LIVE目前是直播空壳子里最好用的！继续几个建议：
1.关于使用遥控器时，频道列表或菜单列表的背景
 1.1背景形状是否可以调置成稍稍带一点点圆角？
![Screenshot_20240414-205206](https://github.com/mlabalabala/box/assets/61964890/67220ee1-c710-4382-9022-48c9a5edcf6e)
![Screenshot_20240414-192457](https://github.com/mlabalabala/box/assets/61964890/78377ebb-f685-4b1b-909c-185cc335ac9d)
 1.2背景颜色是否更改一下，以区别其它作品？以下图片供参考
![看看tv](https://github.com/mlabalabala/box/assets/61964890/b91a8336-3ac2-44a8-8a17-a19eedbd1014)
![乐看tv](https://github.com/mlabalabala/box/assets/61964890/d8f06081-241b-4907-8a35-544c8b5da015)
![灵犀tv](https://github.com/mlabalabala/box/assets/61964890/6d58ad20-ff66-445a-b355-e155191c85e5)
![秒看tv](https://github.com/mlabalabala/box/assets/61964890/b26f0de7-7433-417e-82c7-398fcd41cf05)
2.直播播放界面添加：屏幕左侧上下滑动调整亮度，右侧上下滑动调节音量。可以方便手机使用时进行调节。
![Screenshot_20240419_103453 (2)](https://github.com/mlabalabala/box/assets/61964890/056d8b33-96ae-4dce-95a1-9335316f34bb)
3.关于底部台标信息，再追问一下，当没法连接EPG服务器，或拿不到数据时，是否可以也让台标状态栏显示出来，只是节目信息那里提示：暂无节目信息或精彩节目。图片为派大星没EPG时的状态。
![Screenshot_20240419_105401](https://github.com/mlabalabala/box/assets/61964890/bf161581-b769-4217-8c0f-73c89b177bae)

**Comment by pm20120** [comment]
还有一个问题，不知道是否超纲。在节目列表的第二栏是否可以显示当前播放的EPG信息？请看下图。这样没必要时就不用点右侧的》查看节目信息了。
![乐看tv](https://github.com/mlabalabala/box/assets/61964890/96b4937c-60b1-4521-9433-3c677d59cef2)

**Comment by mlabalabala** [comment]
OK 我抽空看看能不能整

**Comment by mlabalabala** [comment]
### 更新部分功能
- 修改全局比例逻辑
- EPG连接复活，修改默认显示下方EPG信息，当网络EPG可用时，显示网络信息，反之显示暂无信息

### 关于直播版界面添加音量和亮度调整进度条
由于这个直播版初衷是给家里老人的机顶盒或者电视写的，添加的必要性不是很大，如果需要的话，可以使用Jade的横屏版，横屏版的播放页可以显示调整的进度条，其中直播功能也和直播版同步了，

### 节目列表的第二栏显示当前播放的EPG信息
待开发。。。


工作太忙了，随缘更新:)

**Comment by mlabalabala** [comment]
### 更新频道列表的第二栏显示当前播放的EPG信息
![image](https://github.com/mlabalabala/box/assets/91363385/b14759e9-e2e4-4ad2-b3f4-513c7943605e)

**Comment by pm20120** [comment]
今天的更新太好了，请把LIVE版本也重新一下吧。

**Comment by mlabalabala** [comment]
> 今天的更新太好了，请把LIVE版本也重新一下吧。

已同步更新

**Comment by pm20120** [comment]
我遇到一个情况: jadetv 直播版，在加载的直播列表文件较大（>200k）时，会直接闪退，然后再也打不开了，也不能修改列表地址了，只能删除app然后重装，再设置别的直播列表。请大佬看看能不能解决一下。

**Comment by mlabalabala** [comment]
我找时间调试看看吧
