### ISSUE TITLE
能搞一个支持arm64-v8a的quickjs模块吗?

### ISSUE THREAD

**Issue by super963883929** [mlabalabala/box#19]
能搞一个支持arm64-v8a的quickjs模块吗?使用armeabi-v7a的so很多机型都会出现闪退问题,或者你有"quickjs"这个模块so文件的C或者C++代码吗?

**Comment by mlabalabala** [comment]
这个竖屏的项目中有相关支持的64位so，你可以尝试整合一下
https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/tree/main/quickjs/src/main/jniLibs

box项目整合得等一段时间出了，最近没空整 :(

**Comment by super963883929** [comment]
还有一个,我要指出你一个死循环bug,在你的HomeActivity(app/src/main/java/com/github/tvbox/osc/bbox/ui/activity/HomeActivity.java)里面的initData()方法里面369行和415中,初始化成功之后又初始化了,我昨天抓包调试时候才看到的,难怪说运行起来手机那么烫,一秒请求几百次

**Comment by mlabalabala** [comment]
这部分代码怎么说呢，始祖项目加载jar和配置的时候逻辑是这样的，这个项目叉过来之后，这块逻辑没有改过 ... 如果配置文件没有问题的话，正常不会重复请求。如果可以的话，提供一下配置，我本地调试看看
