### ISSUE TITLE
请问添加配置地址后闪退或提示配置失败是啥问题？

### ISSUE THREAD

**Issue by jjj333** [mlabalabala/box#20]
android4.4的华为EC6108V9C

同样的盒子，装的猫影视可以用的http地址，添加到jade里就闪退，https地址全都是配置失败或闪退

请问是不是系统限制，https的地址都用不了？

**Comment by mlabalabala** [comment]
猫影视app是哪个软件呢？

有些https网站比较心得tls，使用安卓4.4系统会出现问题（个人见解）也没有什么好的解决办法，用http或者其他源吧

**Comment by jjj333** [comment]
> 猫影视app是哪个软件呢？
> 
> 有些https网站比较心得tls，使用安卓4.4系统会出现问题（个人见解）也没有什么好的解决办法，用http或者其他源吧

哦，猫影视是我自己取得名字，也是TVbox的修改版，图标是个黑白的猫+影视两个字，我用的地址是http://pandown.pro/tvbox/tvbox.json，在jade上点了确定就闪退回home界面，在猫影视上就没问题

**Comment by mlabalabala** [comment]
我身边没有4.4系统设备，但是这个源测试在电脑的安卓子系统jade上能加载出来，可以尝试更新到新版本试试
![image](https://github.com/user-attachments/assets/a6bb99d9-54c5-466c-808c-cc49d234cec4)
PS：”黑白的猫+影视“ 有没有具体的app名字呢？

**Comment by jjj333** [comment]
> 我身边没有4.4系统设备，但是这个源测试在电脑的安卓子系统jade上能加载出来，可以尝试更新到新版本试试 ![image](https://private-user-images.githubusercontent.com/91363385/348752333-a6bb99d9-54c5-466c-808c-cc49d234cec4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMDgwNTUsIm5iZiI6MTcyMTEwNzc1NSwicGF0aCI6Ii85MTM2MzM4NS8zNDg3NTIzMzMtYTZiYjk5ZDktNTRjNS00NjZjLTgwOGMtY2M0OWQyMzRjZWM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDA1MjkxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiNzk0ZjQyNzVmYzBlYzcyZTNlMmI3ZGM5MmVmMTcyYzI0OTgxYTM5OTM4OWViZDY0NTJkOTAxYzVmMTFjMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wL4_5VIHarQdfH7T4ZUeT_UojoWqtu66wJIVSZxWuN8) PS：”黑白的猫+影视“ 有没有具体的app名字呢？

已经用了网盘里最新的Jade_SHJ_202406242342了。。。。

**Comment by mlabalabala** [comment]
emm。。这两天有机会用了家里的海信电视和移动的魔百盒（都是安卓4.4系统）尝试加载这个[源](http://pandown.pro/tvbox/tvbox.json)，没有遇到闪退的情况，这种情况我不太好找问题了。。。

**Comment by jjj333** [comment]
最后换了安卓9的盒子，还是有这问题，而且之前能用的也会发生配置失败或者ssl handshake错误，估计还是源和我宽带线路配合问题
