### ISSUE TITLE
配置里面的项目怎么填？能举个例子吗？

### ISSUE THREAD

**Issue by lon91ong** [mlabalabala/box#21]
![微信图片_20240811131003](https://github.com/user-attachments/assets/1e21f0ac-b54b-49b9-b30a-d6a2c7c47ebf)
如图所示，**仓库/线路地址**和**自定义配置接口地址**分别是管什么用的？
**自定义EPG**地址又是什么？

**Github加速地址**有什么格式要求吗？比如下面常用的两个该怎么填`https://mirror.ghproxy.com/https://raw.githubusercontent.com/mlabalabala/TVResource/main/boxCfg/live.txt`
`https://fastly.jsdelivr.net/gh/mlabalabala/TVResource@main/boxCfg/live.txt`

**Comment by mlabalabala** [comment]
### 1.仓库地址填多源链接，数据格式可以是多条线路的集合、或者是各种多条线路的集合的集合，数据格式如下
```

// 多条线路的集合 https://gitee.com/mlabalabala/TVResource/blob/main/boxCfg/ori_source.json
{
    "urls": [
        {
            "url": "http://www.饭太硬.com/tv/",
            "name": "🚀饭太硬线路"
        },
        {
            "url": "http://ok321.top/tv/",
            "name": "🚀OK线路"
        }
    ]
}

// 多条线路的集合的集合
{
  "storeHouse": [
    {
      "sourceName": "默认",
      "sourceUrl": "https://raw.githubusercontent.com/mlabalabala/TVResource/main/boxCfg/ori_source.json"
    },
    {
      "sourceName": "起飞",
      "sourceUrl": "https://raw.githubusercontent.com/mlabalabala/TVResource/main/boxCfg/sp_source.json"
    }
  ]
}
```


### 2.配置接口配置地址，例如
- http://www.饭太硬.com/tv/
- http://ok321.top/tv/
- 等等...


### 3.直播源接口配置地址，例如
- https://gitee.com/mlabalabala/TVResource/blob/main/boxCfg/live.txt
- 等等...

### 4.EPG接口配置地址，像CCTV1这个直播台号的直播信息，台标信息都是从epg的接口获取的，已经内置到软件内了几条，如果自己没有这个接口，一般不用动，不影响主要的直播功能

### 5.github仓库加速，原先用于更新和拉取默认配置的，基础信息已经同步到[GITEE仓库](https://gitee.com/mlabalabala/TVResource/)，这个配置已经废弃了，部分代码还没有清理。。。

**Comment by lon91ong** [comment]
[GITEE仓库](https://gitee.com/mlabalabala/TVResource/)访问受限了

**Comment by mlabalabala** [comment]
![Screenshot_2024-08-12-09-31-53-222_mark via](https://github.com/user-attachments/assets/7cc0c233-51dc-48e5-a376-e91e241f1a56)
才看到仓库被自动设置成私有了，暂时先用加速站和github的源吧，我尝试看能不能调整调整
