### ISSUE TITLE
无法打包，用github action 打包出错

### ISSUE THREAD

**Issue by chengxue2020** [mlabalabala/box#22]
无法打包了，用github action 打包出错

**Comment by mlabalabala** [comment]
确实报错了，我抽空看看再改下生成的代码吧

**Comment by chengxue2020** [comment]
感谢大佬

**Comment by mlabalabala** [comment]
编译的脚本文件已经修改，初步判断有几个依赖在远程仓库找不到了，导致打包报错，修改了一下仓库配置，我这边测试通过github编译可以正常打包了 :)
