### ISSUE TITLE
设置源配置，能否增加电视直播源单独添加地址

### ISSUE THREAD

**Issue by Supprise0901** [mlabalabala/box#3]
线路配置及多源配置都不能单独添加电视直播源地址

**Comment by mlabalabala** [comment]
好的

**Comment by mlabalabala** [comment]
参考[大佬项目](https://github.com/takagen99/Box)的自定义直播源逻辑，已添加到项目中，测试可能不太够，使用过程中有BUG再提Issue吧

**Comment by Supprise0901** [comment]
可以再完善下吗，类似tvbox的设置，能否增加，选项，启动时直接进直播
