### ISSUE TITLE
请教如何适配饭阿里

### ISSUE THREAD

**Issue by zhuziwuming** [mlabalabala/box#6]
我使用俊仓库的原始代码打包，用饭的jar不支持阿里推送了。请教是如何适配

**Comment by mlabalabala** [comment]
https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/commit/39f4a28f7d4810cea57f9a4f76728d326a759d0f

参考的这个提交修改app/src/main/java/com/github/tvbox/osc/server/RemoteServer.java内容，这个是XiaoRanLiu3119大佬开发的竖屏版本，但是的有些设备或者因为网络原因还是不能使用玩偶，但是这个横屏TV的box项目里面修改之后是可以正常使用饭阿里的

**Comment by zhuziwuming** [comment]
非常感谢！
