### ISSUE TITLE
默认线路修改无效

### ISSUE THREAD

**Issue by Aijiaobin** [mlabalabala/box#7]
默认线路位置 app/src/main/java/com/github/tvbox/osc/bbox/constant/URL.java
修改默认线路。但是打开默认线路仍然是空的

**Comment by mlabalabala** [comment]
![image](https://github.com/mlabalabala/box/assets/91363385/0a7b66a4-8665-47f7-b5ef-e0d511c5a206)

稍后我会更新一下说明文档 :)

**Comment by Aijiaobin** [comment]
感谢。感谢 成功了。
