### ISSUE TITLE
"自建仓库"无法解析

### ISSUE THREAD

**Issue by OscarKoo** [mlabalabala/box#8]
添加您的"自建仓库"地址, 为什么一直提示"解析配置失败"啊?
哪怕把这个json文件上传到电视盒子里, 利用clan地址, 也是解析失败...

![图片](https://github.com/mlabalabala/box/assets/14313034/8651b09b-2544-41b2-8f4e-6d11adcfab0a)

**Comment by mlabalabala** [comment]
https://github.com/mlabalabala/TVResource/commit/5468f46f9a2cbfb4e00f42db5dcc81789399bae0

修正了JSON格式错误。。。

这个默认仓库原本是给大家提供一个自定配置的思路，很长时间没有动过了，一般情况下维护得比较少。
如果需要的话，可以参考社区有很多大佬提供的配置

这个自建配置使用的是饭的配置@.@。。。
效果和 http://饭太硬.top/tv/ 一样，源更新比本仓库频繁，建议还是使用 http://饭太硬.top/tv/
