### ISSUE TITLE
请问直播默认源地址的修改地方在哪里。

### ISSUE THREAD

**Issue by Aijiaobin** [mlabalabala/box#9]
请问 直播  默认源地址  的修改地方在哪里。

**Comment by Aijiaobin** [comment]
app/src/main/java/com/github/tvbox/osc/bbox/constant/URL.java
这个位置修改的默认直播源地址无效，依然是  http://home.jundie.top:81/Cat/tv/live.txt

**Comment by mlabalabala** [comment]
是添加了默认配置，然后也添加了默认直播源嘛？
如果是这样的话，配置的处理逻辑是：先添加默认直播源，然后加载默认配置，配置内的直播源就会替换配置的默认直播源

**Comment by mlabalabala** [comment]
emm。。。
这个默认直播源在URL.java中可配置，在处理过程中并没有被自动配置的代码

**Comment by Aijiaobin** [comment]
app/src/main/java/com/github/tvbox/osc/bbox/constant/URL.java
修改这个文件的// 默认直播线路
    public static final String DEFAULT_LIVE_URL =“www.baidu.com”
    但是生成APK 。默认的直播线路还是“http://home.jundie.top:81/Cat/tv/live.txt”  没有替换成功。不知道为什么。也不知道这个地址哪来的。没找到地方修改

**Comment by mlabalabala** [comment]
http://home.jundie.top:81/Cat/tv/live.txt这个链接看起来像你添加的默认配置里面的直播源地址

如果需要使用URL.java中的DEFAULT_LIVE_URL添加默认直播源的话，需要在app/src/main/java/com/github/tvbox/osc/bbox/base/App.java的putDefaultApis()方法中添加代码
```
putDefault(HawkConfig.LIVE_URL, URL.DEFAULT_LIVE_URL);
```
这样配置的默认直播源就能生效了

**Comment by Aijiaobin** [comment]
感谢。成功修改。

**Comment by mlabalabala** [comment]
我多说一句哈，这个默认直播源地址显示在URL.java中，是我忘记删除了 : )

我单独把直播功能提取出来打包了一个基于TVBox的live版的安装包，可以直接使用这个默认地址打开也是直播页面，有相关的配置直播源的地方

这个live版的项目是由本项目删减部分代码后的结果，所以没有把代码放到GitHub上

在[**码：6111**](https://bunny6111.lanzouq.com/b04whwgwj)中可以下载到

![image](https://github.com/mlabalabala/box/assets/91363385/b92a9582-d83e-4e7b-a768-1d628091947f)

**Comment by Aijiaobin** [comment]
现在这样就很完美了，TVBOX 配合小雅alist 填充数据。IPTV 利用IPTV_SOURCE 来配置。APP 使用您的程序来自定义名称图标跟背景，内置数据跟源。播放不卡顿，支持TV 手机等各种设备。相当完美
